modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="funmod" 
version="1.0" 
displayName="A Fun Mod" 
logoFile="examplemod.png" 
credits="The_Great_K" 
authors="The_Great_K"
description='''

A Fun Mod to play around with in Creative
I made this Mod for one of my friends

'''